before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - wget https://download.flashcat.cloud/categraf-libs/lib.tar.gz
    - tar zxvf lib.tar.gz
    - rm -rf lib.tar.gz

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

builds:
  - id: linux-slim
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - no_ibex 
      - no_traces
      - no_logs
      - no_prometheus
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version=slim-{{ .Tag }}-{{.Commit}}

archives:
  - id: categraf-slim
    rlcp: true
    builds:
      - linux-slim
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-slim-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*
      - lib/*
      
release:
  github:
    owner: Jungzhang
    name: categraf
  name_template: "v{{ .Version }}"

