before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

builds:
  - id: linux-arm64
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: linux-amd64
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: linux-amd64-cgo
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - enterprise
      - arppacket
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: linux-slim
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - no_ibex 
      - no_traces
      - no_logs
      - no_prometheus
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version=slim-{{ .Tag }}-{{.Commit}}

  - id: linux-metrics-agent
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - no_ibex 
      - no_traces
      - no_logs
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version=slim-{{ .Tag }}-{{.Commit}}

  - id: windows
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}

archives:
  - id: categraf
    rlcp: true
    builds:
      - linux-amd64-cgo
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}-with-cgo-plugin"
    wrap_in_directory: true
    files:
      - conf/*
      - lib/*

  - id: categraf-common
    rlcp: true
    builds:
      - linux-amd64
      - linux-arm64
      - windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*
      - lib/*

  - id: categraf-slim
    rlcp: true
    builds:
      - linux-slim
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-slim-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*
      - lib/*

release:
  github:
    owner: Jungzhang
    name: categraf
  name_template: "v{{ .Version }}"

